from setuptools import setup, find_packages

setup(
    name="TrueWealth AI",
    version="0.1.0",
    author="Md Emon Hasan",
    author_email="iconicemon01@gmail.com",
    description="TrueWealth AI: Your Smart Path to Financial Freedom",
    packages=find_packages(),
    install_requires=[
        "langchain",
        "langchain-community",
        "langchain-huggingface",
        "langchain-groq",
        "langgraph",
        "langchain-core",
        "python-dotenv",
        "chromadb",
        "sentence-transformers",
        "duckduckgo-search",
        "yahoo_fin",
        "tiktoken",
        "pypdf",
        "wikipedia",
        "yahoo-finance",
        "fastapi",
        "uvicorn",
        "pydantic",
        "sqlalchemy",
        "gunicorn",
        "pytest",
        "streamlit",
        "huggingface-hub",
    ],
    classifiers=[
        "Programming Language :: Python :: 3",
        "Framework :: FastAPI",
        "Framework :: Streamlit",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.8",
)
